using MTT;
using System;
using System.Collections.Generic;
using System.IO;
using Microsoft.Build.Framework;
using MSBuildTask = Microsoft.Build.Utilities.Task;
using System.Text.RegularExpressions;

namespace MSBuildTasks
{
    public class ConvertMain : MSBuildTask
    {
        /// <summary>
        /// The current working directory for the convert process
        /// </summary>
        public string WorkingDirectory { get; set; }

        /// <summary>
        /// The directory to save the ts models
        /// </summary>
        public string ConvertDirectory { get; set; }

        /// <summary>
        /// Determines the naming style of the generated files and folders
        /// </summary>
        public string PathStyle
        {
            get => _pathStyle.ToString();
            set => _pathStyle = (PathStyle)Enum.Parse(typeof(PathStyle), value);
        }

        /// <summary>
        /// Determines the naming style of the generated properties
        /// </summary>
        public string PropertyStyle
        {
            get => _propertyStyle.ToString();
            set => _propertyStyle = (PropertyStyle)Enum.Parse(typeof(PropertyStyle), value);
        }

        /// <summary>
        /// Comments at the top of each file that it was auto generated
        /// </summary>
        public bool AutoGeneratedTag { get; set; } = true; //default value if one is not provided;

        /// <summary>
        /// Export an interface or a class
        /// </summary>
        public string ExportStyle
        {
            get => _exportStyle.ToString();
            set => _exportStyle = (ExportStyle)Enum.Parse(typeof(ExportStyle), value);
        }

        /// <summary>
        /// Determines whether to generate numeric or string values in typescript enums
        /// </summary>
        public string EnumValues
        {
            get => _enumValues.ToString();
            set => _enumValues = (EnumValues)Enum.Parse(typeof(EnumValues), value);
        }

        protected MessageImportance LoggingImportance { get; } = MessageImportance.High;  //If its not high then there are no logs

        private readonly ConvertService convertService;

        private EnumValues _enumValues = MTT.EnumValues.Default;

        private PathStyle _pathStyle = MTT.PathStyle.Default;
        private PropertyStyle _propertyStyle = MTT.PropertyStyle.CamelCase;
        private ExportStyle _exportStyle = MTT.ExportStyle.Interface;

        public ConvertMain()
        {
            convertService = new ConvertService(Log.LogMessage);
        }

        public override bool Execute()
        {
            Log.LogMessage(LoggingImportance, "Starting MTT");

            convertService.AutoGeneratedTag = AutoGeneratedTag;
            convertService.ConvertDirectory = ConvertDirectory;
            convertService.WorkingDirectory = WorkingDirectory;
            convertService.EnumValues = _enumValues;
            convertService.PathStyle = _pathStyle;
            convertService.PropertyStyle = _propertyStyle;
            convertService.ExportStyle = _exportStyle;

            var result = convertService.Execute();

            Log.LogMessage(LoggingImportance, "Finished MTT");
            return result;
        }
    }
}
